// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajfufvjjtsnxxyzpicln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqZnVmdmpqdHNueHh5enBpY2xuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MDUxNDcsImV4cCI6MjA2NDA4MTE0N30.G2XTyFRhdcPj9c5yon0hxpvoA3312PBnmsgqvdlP2o8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: false
    }
  }
);